#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include "parse_args.hpp"

// https://www.gnu.org/software/libc/manual/html_node/Example-of-Getopt.html
// returns 0 if options are parsed successfully; nonzero otherwise
Settings ParseArgs(int32_t argc, char **argv) {
  Settings config = {
    1,    // generate base (walls and bottom)
    NULL, // read from stdin
    NULL, // write to stdout
    1.0,  // no z scaling (use raw heightmap values)
    1.0   // minimum base thickness of one unit
  };

  int32_t c;

  // suppress automatic error messages generated by getopt
  opterr = 0;

  while ((c = getopt(argc, argv, "az:b:o:i:m:t:rhs")) != -1) {
    switch (c) {
    case 'z':
      // Z scale (heightmap value units relative to XY)
      if (sscanf(optarg, "%20f", &config.zscale) != 1 || config.zscale <= 0) {
        fprintf(stderr, "Z scale must be a number greater than 0.\n");
        exit(1);
      }
      break;
    case 'b':
      // Base height (default 1.0 units)
      if (sscanf(optarg, "%20f", &config.baseheight) != 1 || config.baseheight < 1) {
        fprintf(stderr, "BASEHEIGHT must be a number greater than or equal to 1.\n");
        exit(1);
      }
      break;
    case 'o':
      // Output file (default stdout)
      config.output = optarg;
      break;
    case 'i':
      // Input file (default stdin)
      config.input = optarg;
      break;
    case 's':
      // surface only mode - omit base (walls and bottom)
      config.base = 0;
      break;
    case '?':
      // unrecognized option OR missing option argument
      switch (optopt) {
      case 'z':
      case 'b':
      case 'i':
      case 'o':
      case 'm':
      case 't':
        fprintf(stderr, "Option -%c requires an argument.\n", optopt);
        break;
      default:
        if (isprint(optopt)) {
          fprintf(stderr, "Unknown option -%c\n", optopt);
        }
        else {
          fprintf(stderr, "Unknown option character \\x%x\n", optopt);
        }
        break;
      }
      exit(1);
      break;
    default:
      // My understand is getopt will return ? for all unrecognized options,
      // so I'm not sure what other cases will be caught here. Perhaps just
      // options specified in optstring that I forget to handle above...
      fprintf(stderr, "Unexpected getopt result: %c\n", optopt);
      exit(1);
      break;
    }
  }

  // should be no parameters left
  if (optind < argc) {
    fprintf(stderr, "Extraneous arguments\n");
    exit(1);
  }

  if (config.input == NULL) {
    std::cout << "No input path set. Use -i to set input path." << std::endl;
    std::exit(1);
  }

  if (config.output == NULL) {
    std::cout << "No output path set. Use -o to set output path." << std::endl;
    std::exit(1);
  }

  return config;
}
